# Generated by Django 4.1 on 2023-06-03 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construct_number', models.CharField(max_length=50)),
                ('receptor', models.CharField(max_length=100)),
                ('DNA_sequence', models.TextField()),
                ('description', models.TextField()),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P', models.CharField(max_length=100)),
                ('Biomass', models.IntegerField()),
                ('expression_system', models.CharField(max_length=100)),
                ('application_time', models.DateTimeField(auto_now_add=True)),
                ('construct_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.constructitem')),
            ],
        ),
    ]
