# Generated by Django 4.1 on 2023-06-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_constructitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationitem',
            name='construct_number',
            field=models.CharField(default=12345, max_length=50),
            preserve_default=False,
        ),
    ]
