# Generated by Django 4.1 on 2023-06-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_applicationitem_construct_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationitem',
            name='construct_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='constructitem',
            name='construct_number',
            field=models.IntegerField(),
        ),
    ]
