# Generated by Django 4.1 on 2023-06-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_applicationitem_construct_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationitem',
            name='construct_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='constructitem',
            name='construct_number',
            field=models.CharField(max_length=50),
        ),
    ]
