# Generated by Django 4.1 on 2023-06-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_applicationitem_construct_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationitem',
            name='application_user',
            field=models.CharField(default='wm', max_length=100),
            preserve_default=False,
        ),
    ]
