# Generated by Django 4.1 on 2023-06-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_applicationitem_application_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationitem',
            old_name='Biomass',
            new_name='biomass',
        ),
        migrations.RemoveField(
            model_name='applicationitem',
            name='construct_item',
        ),
        migrations.AddField(
            model_name='applicationitem',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
