# Generated by Django 4.1 on 2023-06-04 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_applicationitem_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructitem',
            name='application_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
